nelmio_cors:
    defaults:
        origin_regex: false
        allow_credentials: true
        allow_origin: ['http://127.0.0.1:3000', 'https://topscholar-app.herokuapp.com/']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        max_age: 20000
    paths:
        '^/': ~
